name: CrypsiJs CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g npm@latest yarn@latest

      - name: Install Dependencies
        run: yarn

      - name: Execute linter
        run: npm run lint

      - name: Build Typescript
        run: yarn build:ts

      - name: Build CrypsiJs for browser
        run: yarn build:browser:prod